### ISSUE TITLE
Should use 'B' and 'E' phases instead of 'b' and 'e'

### ISSUE THREAD

**Issue by jrmuizel** [samccone/chrome-trace-event#11]
'b' and 'e' are for async events. Changing to 'B' and 'E' makes the events show up in perfetto.

**Comment by mykola-vrmchk** [comment]
> 'b' and 'e' are for async events. Changing to 'B' and 'E' makes the events show up in perfetto.
I also hit this issue, this Repo seems unmaintained, do you know alternatives for perfetto in nodejs?

**Comment by samccone** [comment]
imho totally valid, let's make this change

**Comment by samccone** [comment]
chrome-trace-event@1.0.4
